[package]
name = "my-imap"
version = "0.1.0"
authors = ["Shane Qi <qizengtai@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.4.1"
native-tls = "0.2.7"
mailparse = "0.13.3"
dotenv = "0.15.0"